on:
  workflow_dispatch:

jobs:
  unassign_issues:
    runs-on: ubuntu-latest
    name: Unassign issues
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - name: Unassign issues
        uses: ./unassign-issues
        id: unassign_issues
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          warning_inactive_in_hours: 0
          unassign_inactive_in_hours: 1
          contact_message: 'visit the #casa channel in slack during Tuesdays 6-8 PM PST. Link: https://rubyforgood.herokuapp.com/'
          warning_inactive_message: "just comment if still working on it"
      - name: Print the unassigned issues
        run: echo "Unassigned issues = ${{steps.unassign_issues.outputs.unassigned_issues}}"
      - name: Print the warned issues
        run: echo "Warned issues = ${{steps.unassign_issues.outputs.warned_issues}}"
